name: scxml
description: StateMachine implementation following SCXML standard
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
